"""empty message

Revision ID: a7f049d5700b
Revises: 2ad2c08664e7
Create Date: 2018-07-30 15:36:06.307538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f049d5700b'
down_revision = '2ad2c08664e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_flop', sa.Column('Split_rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_flop', 'Split_rate')
    # ### end Alembic commands ###
